### ISSUE TITLE
Doesn't work with npx

### ISSUE THREAD

**Issue by Graham42** [update/updater-license#6]
```
$ npx -p update -p updater-license update license:new
npx: installed 1191 in 17.559s
[15:02:37] using file ~/home/grahamm/.npm/_npx/15366/lib/node_modules/update/lib/updatefile.js
[15:02:37] starting update.license
[15:02:37] starting update.license:new task
[15:02:37] ✔ running: license:new
[15:02:37] starting update.license:license-new task
[15:02:37] starting update.license.new
[15:02:37] starting update.license.new:default task
[15:02:37] starting update.license.new:license task
[15:02:37] starting update.license.new
[15:02:37] starting update.license.new:choose task
? Choose the license to generate license-mit
[15:02:44] starting update.license.new
TypeError: app.conflicts is not a function
    at file (/home/grahamm/.npm/_npx/15366/lib/node_modules/updater-license/node_modules/generate-license/generators/file.js:10:15)
    at Task.fn (/home/grahamm/.npm/_npx/15366/lib/node_modules/updater-license/node_modules/generate-license/generators/tasks.js:323:12)
    at /home/grahamm/.npm/_npx/15366/lib/node_modules/update/node_modules/composer/lib/task.js:115:22
    at Task.runDeps (/home/grahamm/.npm/_npx/15366/lib/node_modules/update/node_modules/composer/lib/task.js:79:12)
    at Task.run (/home/grahamm/.npm/_npx/15366/lib/node_modules/update/node_modules/composer/lib/task.js:107:8)
    at /home/grahamm/.npm/_npx/15366/lib/node_modules/update/node_modules/composer/lib/flow.js:25:22
    at Update.Composer.build (/home/grahamm/.npm/_npx/15366/lib/node_modules/update/node_modules/composer/index.js:155:10)
    at /home/grahamm/.npm/_npx/15366/lib/node_modules/updater-license/node_modules/generate-license/generator.js:61:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jonschlinkert** [comment]
see [the readme](https://github.com/update/updater-license#what-does-updater-license-do)

**Comment by jonschlinkert** [comment]
sorry I'm not familiar with npx, I jumped the gun. Reopening to see if we can figure this out.
